### PR TITLE
Update VVCEasy.bat

### PR DESCRIPTION
**Pull request by neoOpus**
check and get the UAC for administrator privilege

### CODE REVIEW

**Comment by MartinEesmaa** [comment]
@neoOpus, thank you for making pull request.
Is there any that you could do without creating new window cmd in batchfile?
- Martin Eesmaa

**Comment by neoOpus** [comment]
I found this project (https://github.com/gerardog/gsudo) and it gives the elevated privilege to the same terminal window/tab... so I think you can add it to your project if you think it fits with your requirements...

let me know if you want some help regarding this or some other stuff

**Comment by MartinEesmaa** [comment]
@neoOpus, okay, I guess I have no choise of creating new Windows Terminal window, it will be stuck in old cmd, but I can accept your pull request. I hope the UAC Script will help to users... :)

**Comment by neoOpus** [comment]
> @neoOpus, okay, I guess I have no choise of creating new Windows Terminal window, it will be stuck in old cmd, but I can accept your pull request. I hope the UAC Script will help to users... :)

I send you a second reply to your question, I guess you didn't read it, it is about gsudo which can make what you wanted but it is part of another project that maybe you can include in your distribution...

**Pull request merged**
